/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author alvar
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMFormularioDeAlumnos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMFormularioDeMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMManejoDeInscripciones = new javax.swing.JMenuItem();
        jMManipulacionDeNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMAlumnosPorMateria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumno");

        jMFormularioDeAlumnos.setText("Formulario de Alumno");
        jMFormularioDeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFormularioDeAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(jMFormularioDeAlumnos);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("Materia");

        jMFormularioDeMateria.setText("Formulario de Materia");
        jMFormularioDeMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFormularioDeMateriaActionPerformed(evt);
            }
        });
        jMenu6.add(jMFormularioDeMateria);

        jMenuBar1.add(jMenu6);

        jMenu3.setText("Administracion");

        jMManejoDeInscripciones.setText("Manejo de Inscipciones");
        jMManejoDeInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMManejoDeInscripcionesActionPerformed(evt);
            }
        });
        jMenu3.add(jMManejoDeInscripciones);

        jMManipulacionDeNotas.setText("Manipulacion de Notas");
        jMManipulacionDeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMManipulacionDeNotasActionPerformed(evt);
            }
        });
        jMenu3.add(jMManipulacionDeNotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        jMAlumnosPorMateria.setText("Alumnos por Materia");
        jMAlumnosPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAlumnosPorMateriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMAlumnosPorMateria);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMFormularioDeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFormularioDeAlumnosActionPerformed

        escritorio.removeAll();
        escritorio.repaint();
        GestionAlumnos ga = new GestionAlumnos();
        ga.setVisible(true);
        escritorio.add(ga);
        escritorio.moveToFront(ga);
        
    }//GEN-LAST:event_jMFormularioDeAlumnosActionPerformed

    private void jMFormularioDeMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFormularioDeMateriaActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        GestionMaterias gm = new GestionMaterias();
        gm.setVisible(true);
        escritorio.add(gm);
        escritorio.moveToFront(gm);
        
    }//GEN-LAST:event_jMFormularioDeMateriaActionPerformed

    private void jMManejoDeInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMManejoDeInscripcionesActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        Inscripciones ins = new Inscripciones();
        ins.setVisible(true);
        escritorio.add(ins);
        escritorio.moveToFront(ins);
        
    }//GEN-LAST:event_jMManejoDeInscripcionesActionPerformed

    private void jMManipulacionDeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMManipulacionDeNotasActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        ActualizacionDeNotas an = new ActualizacionDeNotas();
        an.setVisible(true);
        escritorio.add(an);
        escritorio.moveToFront(an);
        
    }//GEN-LAST:event_jMManipulacionDeNotasActionPerformed

    private void jMAlumnosPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlumnosPorMateriaActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        ConsultaDeAlumnosPorMateria cam = new ConsultaDeAlumnosPorMateria();
        cam.setVisible(true);
        escritorio.add(cam);
        escritorio.moveToFront(cam);
    }//GEN-LAST:event_jMAlumnosPorMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMAlumnosPorMateria;
    private javax.swing.JMenuItem jMFormularioDeAlumnos;
    private javax.swing.JMenuItem jMFormularioDeMateria;
    private javax.swing.JMenuItem jMManejoDeInscripciones;
    private javax.swing.JMenuItem jMManipulacionDeNotas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
